### ISSUE TITLE
What version is this project on?

### ISSUE THREAD

**Issue by NevOliver** [Brackeys/RPG-Tutorial#3]
I downloaded the assets and followed the instructions, but something is wrong.  I get a greenish screen and most of the assets are not showing up properly.  I don't see the terrain, but I see a sign and a fireplace and a few light sources.

**Comment by VladTrut** [comment]
Same, the terrain mesh is completely missing in the project. @NevOliver did you find out how to fix it?

**Comment by VladTrut** [comment]
Just got the solution: reimport all assets in the project and update API. Works fine.

**Comment by zurex** [comment]
@NevOliver Just download Blender. What's more, see #2

**Comment by NevOliver** [comment]
I tried re-importing all assets and updating the API... Twice... Didn't fix the problem.

Trying the Blender route.  I don't know how to use it in unity... Any tutorials on how to use Blender in Unity?

**Comment by NevOliver** [comment]
figured it out.  followed all advice and it worked.
