### ISSUE TITLE
Unity 2018.3 beta error 'MinAttribute' is an ambiguous reference

### ISSUE THREAD

**Issue by kara-todd** [Brackeys/RPG-Tutorial#9]
Hello! Apologies if I'm misunderstanding this error. I've been following your tutorial using Unity `2018.0.0b1` and I started getting the following error:

`'MinAttribute' is an ambiguous reference between 'UnityEngine.PostProcessing.MinAttribute' and 'UnityEngine.MinAttribute'` from the `MinDrawer.cs` file...

I was able to fix it by adding a single line, and I've opened a PR for it (#8)

**Edit** (two years later)

Since this comment is still getting attention, I figured I'd post the here as well. The fix from the PR is more minimal all you need to do is add one line to the top of  both `MinDrawer.cs` files:

`using MinAttribute = UnityEngine.PostProcessing.MinAttribute;`

The ambiguous reference error is caused by multiple possibilities for the `MinAttribute` function existing. In this case, we specify that we need to use the one from Unity Engine. (e.g. `UnityEngine.PostProcessing.MinAttribute`.) You can read more about this in the [C# using directive docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive).

**Comment by isasaurio** [comment]
Change the MinDrawer.cs to this:

```
using UnityEngine;
using UnityEngine.PostProcessing;

namespace UnityEditor.PostProcessing
{
    [CustomPropertyDrawer(typeof(UnityEngine.PostProcessing.MinAttribute))]
    sealed class MinDrawer : PropertyDrawer
    {
        public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
        {
            UnityEngine.PostProcessing.MinAttribute attribute = (UnityEngine.PostProcessing.MinAttribute)base.attribute;

            if (property.propertyType == SerializedPropertyType.Integer)
            {
                int v = EditorGUI.IntField(position, label, property.intValue);
                property.intValue = (int)Mathf.Max(v, attribute.min);
            }
            else if (property.propertyType == SerializedPropertyType.Float)
            {
                float v = EditorGUI.FloatField(position, label, property.floatValue);
                property.floatValue = Mathf.Max(v, attribute.min);
            }
            else
            {
                EditorGUI.LabelField(position, label.text, "Use Min with float or int.");
            }
        }
    }
}
```

**Comment by OnlyHardOfficial** [comment]
Thanks Man! Perfectly

**Comment by CrandellWS** [comment]
https://github.com/Unity-Technologies/PostProcessing/issues/725#issuecomment-447615187

**Comment by Sabbir12488** [comment]
Thanks bro

**Comment by srktnc** [comment]
all `MinAttribute` change to `UnityEngine.PostProcessing.MinAttribute`

**Comment by hyperflyer** [comment]
You can also just "using MinAttribute = UnityEngine.PostProcessing.MinAttribute;"

**Comment by baselsaad** [comment]
> 
> 
> Change the MinDrawer.cs to this:
> 
> ```
> using UnityEngine;
> using UnityEngine.PostProcessing;
> 
> namespace UnityEditor.PostProcessing
> {
>     [CustomPropertyDrawer(typeof(UnityEngine.PostProcessing.MinAttribute))]
>     sealed class MinDrawer : PropertyDrawer
>     {
>         public override void OnGUI(Rect position, SerializedProperty property, GUIContent label)
>         {
>             UnityEngine.PostProcessing.MinAttribute attribute = (UnityEngine.PostProcessing.MinAttribute)base.attribute;
> 
>             if (property.propertyType == SerializedPropertyType.Integer)
>             {
>                 int v = EditorGUI.IntField(position, label, property.intValue);
>                 property.intValue = (int)Mathf.Max(v, attribute.min);
>             }
>             else if (property.propertyType == SerializedPropertyType.Float)
>             {
>                 float v = EditorGUI.FloatField(position, label, property.floatValue);
>                 property.floatValue = Mathf.Max(v, attribute.min);
>             }
>             else
>             {
>                 EditorGUI.LabelField(position, label.text, "Use Min with float or int.");
>             }
>         }
>     }
> }
> ```

thanks bro 3>

**Comment by ZoeDreams** [comment]
thank you, worked like a charm! also to clarify you need to make sure to use this typeof reference on ln(6)
```c#
[CustomPropertyDrawer(typeof(UnityEngine.PostProcessing.MinAttribute))]
```
and access the attribute like this on ln(11):
```c#
UnityEngine.PostProcessing.MinAttribute attribute = (UnityEngine.PostProcessing.MinAttribute)base.attribute;
```

**Comment by pycache-games** [comment]
which version did brackeys use?

**Comment by yusuf6666** [comment]
> Hello! Apologies if I'm misunderstanding this error. I've been following your tutorial using Unity `2018.0.0b1` and I started getting the following error:
> 
> `'MinAttribute' is an ambiguous reference between 'UnityEngine.PostProcessing.MinAttribute' and 'UnityEngine.MinAttribute'` from the `MinDrawer.cs` file...
> 
> I was able to fix it by adding a single line, and I've opened a PR for it (#8)
> 
> **Edit** (two years later)
> 
> Since this comment is still getting attention, I figured I'd post the here as well. The fix from the PR is more minimal all you need to do is add one line to the top of both `MinDrawer.cs` files:
> 
> `using MinAttribute = UnityEngine.PostProcessing.MinAttribute;`
> 
> The ambiguous reference error is caused by multiple possibilities for the `MinAttribute` function existing. In this case, we specify that we need to use the one from Unity Engine. (e.g. `UnityEngine.PostProcessing.MinAttribute`.) You can read more about this in the [C# using directive docs](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive).

Dude haha thank you so much

**Comment by ADENIXS44** [comment]
Please how can I solve this problem? Command CmdPlayerShot must be declared inside a NetworkBehaviour (at System.Void PlayerShoot::CmdPlayerShot(System.String))
UnityEngine.Debug:LogError (object)

This is my Script.

using Mirror;
using UnityEngine;

public class PlayerShoot : MonoBehaviour
{

    private const string PLAYER_TAG = "player";

    public PlayerWeapon weapon;

    [SerializeField]
    private Camera cam;

    [SerializeField]
    private LayerMask mask;

    void Start()
    {
        if (cam == null)
        {
            Debug.LogError("PlayerShoot : No camera referenced");
            this.enabled = false;
        }
    }

    void Update()
    {

        if (Input.GetButtonDown("Fire1"))
        {
            Shoot ();
        }
    }

    [Client]
    void Shoot()
    {
        RaycastHit _hit;
        if (Physics.Raycast(cam.transform.position, cam.transform.forward, out _hit, weapon.range, mask) )
        {
            if (_hit.collider.tag == PLAYER_TAG)
            {
                CmdPlayerShot(_hit.collider.name);
            }

            
        }
        

    }

    [Command(requiresAuthority = false)]
    void CmdPlayerShot (string _ID)
    {
        Debug.Log(_ID + "has been shot.");

    }

}

**Comment by ADENIXS44** [comment]
This is the script it says I should declare on

using Mirror;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.Compilation;
using UnityEngine;
using UnityAssembly = UnityEditor.Compilation.Assembly;

namespace Mirror.Weaver
{
    public static class CompilationFinishedHook
    {
        const string MirrorRuntimeAssemblyName = "Mirror";
        const string MirrorWeaverAssemblyName = "Mirror.Weaver";

        // delegate for subscription to Weaver warning messages
        public static Action<string> OnWeaverWarning;
        // delete for subscription to Weaver error messages
        public static Action<string> OnWeaverError;

        // controls weather Weaver errors are reported direct to the Unity console (tests enable this)
        public static bool UnityLogEnabled = true;

        // warning message handler that also calls OnWarningMethod delegate
        static void HandleWarning(string msg)
        {
            if (UnityLogEnabled) Debug.LogWarning(msg);
            OnWeaverWarning?.Invoke(msg);
        }

        // error message handler that also calls OnErrorMethod delegate
        static void HandleError(string msg)
        {
            if (UnityLogEnabled) Debug.LogError(msg);
            OnWeaverError?.Invoke(msg);
        }

        [InitializeOnLoadMethod]
        public static void OnInitializeOnLoad()
        {
            CompilationPipeline.assemblyCompilationFinished += OnCompilationFinished;

            // We only need to run this once per session
            // after that, all assemblies will be weaved by the event
            if (!SessionState.GetBool("MIRROR_WEAVED", false))
            {
                // reset session flag
                SessionState.SetBool("MIRROR_WEAVED", true);
                SessionState.SetBool("MIRROR_WEAVE_SUCCESS", true);

                WeaveExistingAssemblies();
            }
        }



        public static void WeaveExistingAssemblies()
        {
            foreach (UnityAssembly assembly in CompilationPipeline.GetAssemblies())
            {
                if (File.Exists(assembly.outputPath))
                {
                    OnCompilationFinished(assembly.outputPath, new CompilerMessage[0]);
                }
            }

#if UNITY_2019_3_OR_NEWER
            EditorUtility.RequestScriptReload();
#else
            UnityEditorInternal.InternalEditorUtility.RequestScriptReload();
#endif
        }

        static string FindMirrorRuntime()
        {
            foreach (UnityAssembly assembly in CompilationPipeline.GetAssemblies())
            {
                if (assembly.name == MirrorRuntimeAssemblyName)
                {
                    return assembly.outputPath;
                }
            }
            return "";
        }

        static bool CompilerMessagesContainError(CompilerMessage[] messages)
        {
            return messages.Any(msg => msg.type == CompilerMessageType.Error);
        }

        static void OnCompilationFinished(string assemblyPath, CompilerMessage[] messages)
        {
            // Do nothing if there were compile errors on the target
            if (CompilerMessagesContainError(messages))
            {
                Debug.Log("Weaver: stop because compile errors on target");
                return;
            }

            // Should not run on the editor only assemblies
            if (assemblyPath.Contains("-Editor") || assemblyPath.Contains(".Editor"))
            {
                return;
            }

            // don't weave mirror files
            string assemblyName = Path.GetFileNameWithoutExtension(assemblyPath);
            if (assemblyName == MirrorRuntimeAssemblyName || assemblyName == MirrorWeaverAssemblyName)
            {
                return;
            }

            // find Mirror.dll
            string mirrorRuntimeDll = FindMirrorRuntime();
            if (string.IsNullOrEmpty(mirrorRuntimeDll))
            {
                Debug.LogError("Failed to find Mirror runtime assembly");
                return;
            }
            if (!File.Exists(mirrorRuntimeDll))
            {
                // this is normal, it happens with any assembly that is built before mirror
                // such as unity packages or your own assemblies
                // those don't need to be weaved
                // if any assembly depends on mirror, then it will be built after
                return;
            }

            // find UnityEngine.CoreModule.dll
            string unityEngineCoreModuleDLL = UnityEditorInternal.InternalEditorUtility.GetEngineCoreModuleAssemblyPath();
            if (string.IsNullOrEmpty(unityEngineCoreModuleDLL))
            {
                Debug.LogError("Failed to find UnityEngine assembly");
                return;
            }

            HashSet<string> dependencyPaths = GetDependecyPaths(assemblyPath);
            dependencyPaths.Add(Path.GetDirectoryName(mirrorRuntimeDll));
            dependencyPaths.Add(Path.GetDirectoryName(unityEngineCoreModuleDLL));
            Log.Warning = HandleWarning;
            Log.Error = HandleError;

            if (!Weaver.WeaveAssembly(assemblyPath, dependencyPaths.ToArray()))
            {
                // Set false...will be checked in \Editor\EnterPlayModeSettingsCheck.CheckSuccessfulWeave()
                SessionState.SetBool("MIRROR_WEAVE_SUCCESS", false);
                if (UnityLogEnabled) Debug.LogError("Weaving failed for: " + assemblyPath);
            }
        }

        static HashSet<string> GetDependecyPaths(string assemblyPath)
        {
            // build directory list for later asm/symbol resolving using CompilationPipeline refs
            HashSet<string> dependencyPaths = new HashSet<string>
            {
                Path.GetDirectoryName(assemblyPath)
            };
            foreach (UnityAssembly unityAsm in CompilationPipeline.GetAssemblies())
            {
                if (unityAsm.outputPath == assemblyPath)
                {
                    foreach (string unityAsmRef in unityAsm.compiledAssemblyReferences)
                    {
                        dependencyPaths.Add(Path.GetDirectoryName(unityAsmRef));
                    }
                }
            }

            return dependencyPaths;
        }
    }

}

**Comment by Curran-H** [comment]
Perfect fix, lifesaver. I had no idea what I was looking at -- Imported the Flooded Grounds pack from Sandro T on Unity and was getting this strange issue! Quickest fix ever, though. Github gold for you

**Comment by Stigmamax** [comment]
Merci beaucoup
